[package]
name = "omnis-bouncer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
axum = { version = "0.8", features = ["http2", "multipart"] }
axum-reverse-proxy = { version = "1.0", features = ["tls"] }
deadpool-redis = { version = "0.22", features = ["rt_tokio_1"] }
futures-util = "0.3"
http-body-util = "0.1"
hyper-util = "0.1"
include_dir = "0.7"
redis = { version = "0.32", features = ["tokio-rustls-comp"] }
serde_json = "1.0"
tokio = { version = "1.47", features = ["full"] }
tower = "0.5"
tower-cookies = "0.11"
tower-http = { version = "0.6", features = ["auth", "compression-full", "decompression-full", "timeout", "trace", "util", "validate-request"] }
tower-serve-static = { version = "0.1", features = ["metadata"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing = "0.1"
uuid = { version = "1.18", features = ["fast-rng", "v4"] }

[dev-dependencies]
tracing-test = "0.2.5"
