name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: 'ui/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: UI Lint
        run: pnpm run lint-ci

      - name: UI Format
        run: pnpm run format-ci

      - name: UI Test
        run: pnpm run test

      - name: UI Build
        run: pnpm run build

      - uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: dist

  server:
    runs-on: ubuntu-latest
    needs: ui
    env:
      CARGO_TERM_COLOR: always

    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - uses: actions/download-artifact@v5
        with:
          name: ui-dist
          path: ui/dist

      - name: Install Rust Toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup default stable
          rustup component add clippy rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --profile test --verbose

      - name: Lint
        run: cargo clippy --all -- -D warnings

      - name: Code Format
        run: cargo fmt --all -- --check

      - name: Setup Redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: 6
          redis-port: 6379

      - name: Run Tests
        run: cargo test --profile test --verbose
        env:
          TEST_REDIS_URI: redis://127.0.0.1:6379/0
