name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: Cache Crates
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ./ui/dist
            ./target
            ~/.cargo
          key: test-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            test-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
            test-${{ runner.os }}-
      - name: Create fake UI build artifacts for testing
        run: mkdir ui/dist && mkdir ui/dist/assets && touch ui/dist/assets/favicon.ico && touch ui/dist/assets/index.html
      - name: Build
        run: cargo build --profile test --verbose
      - name: Setup Redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: 6
          redis-port: 6379
      - name: Run Tests
        run: cargo test --profile test --verbose
        env:
          TEST_REDIS_URI: redis://127.0.0.1:6379/0
